create admin landing page
Code-4-Community/jpal-frontend pull request #56
Opened 2021-11-15 17:51 UTC by djung335

I'm not super sure what to include in terms of testing, so any feedback in that area would be much appreciated! Not super sure what the standard is for a frontend ticket so there are probably some things that are missing. Here's how it looks:
![image](https://user-images.githubusercontent.com/44933949/141830002-80f50bca-d5f9-498e-bf9d-4e137d80b1a3.png)

in addition, Ryan mentioned using a date formatting library to parse the dates, but is it absolutely necessary? If we just drop the characters at the end of the day part of the date I think it looks fine, but that also might not be my call so please let me know what you think!

2021-11-15 18:39 UTC, atulyamiglani requested changes

2021-11-15 18:39 UTC, atulyamiglani commented on src/components/adminLandingPage/SurveyTable.tsx
> +const SurveyTable: React.FC = () => (
Data should come in as props so that you can use it in this component. You should also have a type for it. 🧐

2021-11-15 18:41 UTC, atulyamiglani commented
The other cypress tests broke 🥲 Also you should run ```npm run prepush:fix``` before pushing it.

2021-12-07 14:50 UTC, rymaju commented on src/App.tsx
> +
Spacing is kind of funky here, definitely remember to run the linter

2021-12-07 14:50 UTC, rymaju commented on src/App.tsx
> -              <Route path="/admin" exact component={() => <LandingPage />} />
🤔 this should break a Cypress test but its not a big fix. If you want I can push a quick fix or we can pair?

2021-12-07 14:50 UTC, rymaju commented on src/components/adminLandingPage/SurveyTable.tsx
> +const SurveyTable: React.FC = () => (
We would lift out `data` to the `Page` component and pass it in there

2021-12-07 14:50 UTC, rymaju commented on src/components/adminLandingPage/SurveyTableRow.tsx
> +const dateFormatter = (date: Date) =>
Seems like this should belong somewhere else? We might want to reuse this code eventually. Plus, I would love some tests on this function (or an explanatory purpose statement) because I have no idea what the output will look like

2021-12-07 14:50 UTC, rymaju commented on src/pages/AdminLandingPage.tsx
> +
Building on my previous comment:

Here we would (for now) hardcode `data`, then pass it to SurveyTable below i.e. `<SurveyTable data={data}/>`

2021-12-10 20:00 UTC, rymaju approved these changes
LGTM

2021-12-10 20:03 UTC, atulyamiglani commented
LGTM!

2021-12-10 20:04 UTC, atulyamiglani commented
LGTM!

2021-12-10 20:16 UTC, atulyamiglani approved these changes
LGTM! 😅

2021-12-12 17:27 UTC, onb6 approved these changes
LGTM!

2021-12-13 19:45 UTC, merged