Update admin table to have first and last name
Code-4-Community/jpal-frontend pull request #64
Opened 2022-02-02 21:53 UTC by michelle-vel

Summary: 
- added first and last name to admin table
- added test
- added key to admin table map function
- fixed api url environment variable 

<img width="852" alt="Screen Shot 2022-02-02 at 4 35 54 PM" src="https://user-images.githubusercontent.com/96444785/152243201-b11710e9-5ccd-49a3-9715-88a136bbc7a0.png">

2022-02-02 21:55 UTC, onb6 approved these changes
WOOT WOOT

2022-02-02 21:55 UTC, onb6 commented
> WOOT WOOT

This review probably shouldn't really count since we paired on this

2022-02-03 15:28 UTC, rymaju requested changes
Very minor change, just want to also update the column header name. Otherwise great work!

2022-02-03 15:28 UTC, rymaju commented on src/components/researcherLandingPage/AdminTable.tsx
> +          <AdminTableRow key={admin.email} admin={admin} />
🔧 Can we change the table header from "Admin" to "Name"?

⭐ Bonus points if you make this table sortable by the name column as well

2022-02-03 15:28 UTC, rymaju commented on src/pages/researcherLandingPage/ResearcherLandingPage.test.tsx
> +    const testFirstName = await screen.findByText(/first/);
💯

2022-02-13 17:44 UTC, onb6 commented on src/components/researcherLandingPage/AdminTable.tsx
> +          <AdminTableRow key={admin.email} admin={admin} />
Fixed!

2022-02-15 18:06 UTC, rymaju approved these changes
LGTM

2022-02-28 15:50 UTC, merged