Added date to frontend dto and added it to admin dashboard
Code-4-Community/jpal-frontend pull request #68
Opened 2022-02-13 20:56 UTC by DerekL27

also fixed the function that makes dates readable

2022-02-15 17:39 UTC, rymaju requested changes
Please remove the changes to package lock! In the future make sure your node and npm versions are up to date (npm i -g npm@latest)

2022-02-15 17:39 UTC, rymaju commented
also screenshots would be appreciated!

2022-02-16 22:00 UTC, rymaju requested changes

2022-02-16 22:00 UTC, rymaju commented on src/components/adminLandingPage/SurveyTableRow.tsx
> +  new Date(date).toLocaleString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
❓Why do you need to wrap it with new date here? Also be careful, you might need more parens around (new Date(...))

2022-02-16 22:00 UTC, rymaju commented on src/pages/adminLandingPage/AdminLandingPage.test.tsx
> +    date: new Date(),
🔧This is stateful code, the date will change depending on when you run the test. Instead use a set date in the past

2022-02-16 22:12 UTC, DerekL27 commented on src/components/adminLandingPage/SurveyTableRow.tsx
> +  new Date(date).toLocaleString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
for some reason it is a string and won't be parsed correctly unless I convert it to a date object

2022-02-16 22:21 UTC, rymaju commented on src/components/adminLandingPage/SurveyTableRow.tsx
> +  new Date(date).toLocaleString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
Right, which means it breaks the signature of this function. Your solution does not actually fix the problem

You need to convert the string (currently incorrectly typed as a Date) to a Date *before* calling this function, I suspect that the return type of the api request is wrong.

2022-02-16 22:24 UTC, rymaju commented on src/components/adminLandingPage/SurveyTableRow.tsx
> +  new Date(date).toLocaleString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
You have a few options, simplest being going to apiClient.getSurveys (or whatever its called) and converting the date string to a date obj before returning the value

It would be best to use a schema parser like zod to do this for us in the future. You can use this approach instead if you want

2022-02-27 20:57 UTC, DerekL27 commented
skipping the pact test because it broke and Ryan and I couldn't fix it @onb6 

"Pact sucks" - @rymaju

2022-02-27 23:49 UTC, rymaju requested changes
Please update to package lock version 2, install the latest npm and then npm install again!

2022-03-06 20:03 UTC, rymaju approved these changes
LGTM

2022-03-06 20:20 UTC, onb6 approved these changes
LGTM!!

2022-03-06 20:22 UTC, merged