created component for redirect
Code-4-Community/jpal-frontend pull request #78
Opened 2022-03-24 02:23 UTC by DerekL27

### ℹ️ Issue

Closes [clickup ticket link](https://app.clickup.com/t/24n9en6)

### 📝 Description

Briefly list the changes made to the code:

- Added component for auto redirecting to the correct landing page

### ✔️ Verification

Tested it manually, no tests written yet.

2022-03-26 18:11 UTC, rymaju requested changes

2022-03-26 18:11 UTC, rymaju commented on src/App.tsx
> +roleMap.set(Role.RESEARCHER, "/researcher")
🔧 No need to use a ES6 Map here, just use a plain old object

```suggestion
// Map with all the roles mapped to their landing pages
const roleMap = {
  [Role.ADMIN]: "/private",
  [Role.RESEARCHER]: "/researcher",
}
```

2022-03-26 18:11 UTC, rymaju commented on src/components/LandingPageRedirect.tsx
> +          <AmplifySignOut />;
❓ Why show sign out here while loading?

2022-03-26 18:11 UTC, rymaju commented on src/components/LandingPageRedirect.tsx
> +          <AmplifySignOut />;
Or at all?

2022-03-26 18:11 UTC, rymaju commented on src/components/LandingPageRedirect.tsx
> +const LandingPageRedirect: ({rolesMap}: { rolesMap: any }) => (JSX.Element) = ({ rolesMap }) => {
🔧 💭 I personally dislike function components that have multiple return statements.

Prefer to return a single piece of JSX and template in whatever you need with conditional logic.

2022-03-27 18:30 UTC, onb6 commented on src/components/LandingPageRedirect.tsx
> +          <AmplifySignOut />;
We do not need signout here because it was removed in another PR

2022-04-03 19:34 UTC, onb6 requested changes
Sorry just those small changes

2022-04-03 19:34 UTC, onb6 commented on src/components/LandingPageRedirect.tsx
> +// TODO: Fix signature
Is this still a todo?

2022-04-03 19:34 UTC, onb6 commented on src/components/LandingPageRedirect.tsx
> +          <AmplifySignOut />
We can remove this line, only the error should display

2022-04-03 19:34 UTC, onb6 commented on src/components/LandingPageRedirect.tsx
> +          <AmplifySignOut />
No need for logout

2022-04-05 14:55 UTC, onb6 commented on src/components/LandingPageRedirect.tsx
> +      {user && rolesMap[user.role] && user.role !== undefined && (
This should be an error, not the sign out button. The header handles sign out

2022-04-14 19:29 UTC, onb6 commented on src/components/LandingPageRedirect.tsx
> +          <AmplifySignOut />
This was wrong lol my b

2022-04-14 19:30 UTC, onb6 commented on src/components/LandingPageRedirect.tsx
> +      {user && rolesMap[user.role] && user.role !== undefined && (
Ignore me acutally I think im wrong

2022-04-14 19:31 UTC, onb6 commented on src/components/LandingPageRedirect.tsx
> +            An error occurred while fetching your user information. Please sign out and try again.
Im sorry, I was wrong, we do need the amplify logout here I was being a dummy

2022-04-14 19:31 UTC, onb6 commented on src/components/LandingPageRedirect.tsx
> +// TODO: Fix signature
^^

2022-04-21 21:36 UTC, rymaju commented on src/components/LandingPageRedirect.tsx
> +// TODO: Fix signature
^^

2022-04-21 21:37 UTC, rymaju reviewed
Olivia is right!

2022-04-25 11:53 UTC, vrautela commented on src/components/LandingPageRedirect.tsx
> +      {user && rolesMap[user.role] && user.role !== undefined && (
⛏️ I think you should move the check for `user.role !== undefined` to be ahead of where it is used so that the short-circuiting behavior works as expected (also pretty sure you can get away with just `user.role` instead of `user.role !== undefined`)

2022-04-25 11:55 UTC, vrautela commented on src/components/LandingPageRedirect.tsx
> +      {user && rolesMap[user.role] && user.role !== undefined && (
Also you should add the `user.role !== undefined` check to line 32 as well

2022-04-25 11:58 UTC, vrautela commented on src/components/LandingPageRedirect.tsx
> +      {user && !rolesMap[user.role] && <AmplifySignOut />}
```suggestion
      {((user && user.role && !rolesMap[user.role]) || (!user.role)) && <AmplifySignOut />}
```

2022-04-25 12:00 UTC, vrautela submitted a review, later dismissed
Overall looks good. I had a few small comments about the logic statements

2022-04-30 19:56 UTC, onb6 approved these changes
LGTM!

2022-04-30 20:21 UTC, rymaju approved these changes
LGTM

2022-05-01 19:23 UTC, merged