add patch request when starting survey
Code-4-Community/jpal-frontend pull request #82
Opened 2022-04-03 19:44 UTC by jgfino

### ℹ️ Issue

Closes [clickup ticket link](https://app.clickup.com/t/2gudw08)

### 📝 Description

- Added the frontend sending a PATCH request to the backend when a reviewer starts a survey by clicking "complete their survey" so that the backend can keep track of survey progress.

### ✔️ Verification

Tested manually by comparing with database and added into end-to-end tests

2022-04-04 00:31 UTC, wwohlers requested changes
Good start, a couple minor things

2022-04-04 00:31 UTC, wwohlers commented on src/api/apiClient.ts
> +    this.patch(`/assignment/${assignmentUuid}`, null).catch((BadRequestException) => {
Should return this promise: `return this.patch(...)`

2022-04-04 00:31 UTC, wwohlers commented on src/components/survey/SurveyViewController.tsx
> +          confirmYouth={async () => {
This should be extracted into a separate callback function. Ideally, we should also use `useCallback()` with `getCurrentYouth()` as a dependency.

2022-04-05 14:51 UTC, rymaju commented
^ What Bill said

2022-04-12 14:51 UTC, onb6 commented on src/components/survey/SurveyViewController.tsx
> + * Responsible for rendering the current surview depending on the state of the survey view state machine.
⛏typo i think

2022-04-12 14:53 UTC, onb6 commented on src/components/survey/SurveyViewController.tsx
> +          confirmYouth={confirmYouthCallback}
this is a very clean solution!

2022-04-14 20:58 UTC, rymaju requested changes

2022-04-14 20:58 UTC, rymaju commented on src/api/apiClient.ts
> +    return this.patch(`/assignment/${assignmentUuid}`, null).catch((BadRequestException) => {
What is the purpose of this catch? It simply throws the error, which is what it does anyways.

Also, `BadRequestException` -> `badRequestException` since it is a parameter, not a type.

2022-04-14 20:58 UTC, rymaju commented on src/components/survey/SurveyViewController.tsx
> +    send('CONFIRM');
🔧 Should we still send the confirm if the API request failed?

2022-04-17 18:36 UTC, jgfino commented on src/api/apiClient.ts
> +    return this.patch(`/assignment/${assignmentUuid}`, null).catch((BadRequestException) => {
Fixed!

2022-04-17 18:36 UTC, jgfino commented on src/components/survey/SurveyViewController.tsx
> +    send('CONFIRM');
Fixed!

2022-04-21 21:35 UTC, rymaju commented on cypress/integration/reviewer-survey-flow.spec.ts
> +    .its('request.body')
Why are we asserting that the body is empty?

2022-04-21 21:35 UTC, rymaju commented on src/components/survey/SurveyViewController.tsx
> + * Responsible for rendering the current surview depending on the state of the survey view state machine.
nah all the cool kids call them surviews 😎

2022-04-21 21:35 UTC, rymaju approved these changes
LGTM

2022-04-26 00:29 UTC, wwohlers approved these changes

2022-04-30 20:09 UTC, merged