removes search icon from landing pages when other stuff is being rendered
Code-4-Community/jpal-frontend pull request #86
Opened 2022-04-11 04:06 UTC by atulyamiglani

### ℹ️ Issue

Closes [clickup ticket link](https://app.clickup.com/t/2nuqdtr)

### 📝 Description
This PR solves the issue of the search icon being rendered when the user menu was clicked. 

Briefly list the changes made to the code:

- added a state to track when the user avatar is clicked  
- the search icon is not rendered when the user avatar is clicked 

### ✔️ Verification

What steps did you take to verify your changes work? These should be clear enough for someone to be able to clone the branch and follow the steps themselves. 

### Before - 
<img width="1440" alt="Screen Shot 2022-04-10 at 11 55 56 PM" src="https://user-images.githubusercontent.com/50613521/162663347-175ae8ba-f588-45a4-8fe8-f75810a91c75.png">

### After - 
<img width="1440" alt="Screen Shot 2022-04-10 at 11 54 51 PM" src="https://user-images.githubusercontent.com/50613521/162663380-954d9b17-fb85-42bf-a466-1c59f612b9e8.png">
<img width="1440" alt="Screen Shot 2022-04-10 at 11 54 59 PM" src="https://user-images.githubusercontent.com/50613521/162663392-129cb638-9add-47d5-92e8-fcb4efcc4969.png">

Provide screenshots of any new components, styling changes, or pages. 

### 🏕️ (Optional) Future Work / Notes

Did you notice anything ugly during the course of this ticket? Any bugs, design challenges, or unexpected behavior? Write it down so we can clean it up in a future ticket!

2022-04-21 21:42 UTC, rymaju approved these changes
🤔 This is great; although, I wonder if there's a CSS solution for this? Actually removing the element seems like a little overkill. Doesn't matter too much to me though. I would have assumed bumping or lowering the z-index of the affected elements would do the trick but 🤷‍♂️

2022-04-21 21:42 UTC, rymaju commented
😍 love the screenshots!

2022-04-21 22:30 UTC, onb6 commented
> 

Yeah I have been thinking about this as well. The issue that I see with this approach is, if you resize the window so there is no overlap, then the icon will still disappear, which isn't really what we want. Like Ryan, my mind also went to z-index. I played around with it a bit earlier today and it seems Chakra is a bit resistant z-index. Despite that, I think that it is worth finding a CSS solution with layered rendering would be a better option, because while this solves the original problem, it leaves us with a new one. I feel so bad because you put so much work into this and did a really great job!!

2022-04-22 21:12 UTC, atulyamiglani commented
That's a good point! I can look into it and find a CSS solution for this!

2022-04-26 00:34 UTC, wwohlers requested changes

2022-04-26 00:34 UTC, wwohlers commented on src/App.tsx
> +  const [userAvatarClicked, setUserAvatarClicked] = React.useState(false);
This is kind of awkward since it's used in multiple components (deeply), we should use context or store instead. Since I don't think we have a store, we should just use context.

2022-04-26 01:17 UTC, atulyamiglani commented on src/App.tsx
> +  const [userAvatarClicked, setUserAvatarClicked] = React.useState(false);
ya that makes sense. I changed the code tho lol, using zIndex makes it very easy!

2022-04-26 01:52 UTC, rymaju approved these changes
LGTM
Less is more!

2022-04-30 19:57 UTC, onb6 approved these changes
Beautiful!

2022-05-01 20:35 UTC, wwohlers approved these changes

2022-05-01 20:52 UTC, merged