Ob styling fixes
Code-4-Community/jpal-frontend pull request #87
Opened 2022-04-14 19:23 UTC by onb6

### ℹ️ Issue

Closes [clickup ticket link](https://app.clickup.com/t/2gumtpd)
Closes [clickup ticket link](https://app.clickup.com/t/2px5q0t)
among other things

### 📝 Description

Briefly list the changes made to the code:

- Changed every instance of youth to worker (and changed some sentences so that made sense)
- Updated control explanation and survey explanation so they were good enough for demo
- Other minor word tweaks requested by Sara
- Center login page
- Styling for add new admin page (now matches figma)

### ✔️ Verification

Compare with Figma, manual testing

Provide screenshots of any new components, styling changes, or pages. 
<img width="1427" alt="Screen Shot 2022-04-14 at 3 22 52 PM" src="https://user-images.githubusercontent.com/71183262/163461592-df6c9565-1df6-4ad0-bf9f-abb360b9c71e.png">
<img width="1416" alt="Screen Shot 2022-04-14 at 3 22 45 PM" src="https://user-images.githubusercontent.com/71183262/163461653-f0024015-da44-4391-8b7a-d96ffaa425e3.png">

### 🏕️ (Optional) Future Work / Notes

Still lots of styling fixes. Customization of explanatory text will be implemented at some point, as discussed in demo.

2022-04-14 22:29 UTC, jgfino requested changes
Looks great! Just one small typo :)

2022-04-15 15:49 UTC, atulyamiglani commented on src/components/survey/ConfirmReviewerIdentity.tsx
> +            {' '}
why this?

2022-04-15 15:50 UTC, atulyamiglani approved these changes
Looks great!

2022-04-21 15:14 UTC, onb6 commented on src/components/survey/ConfirmReviewerIdentity.tsx
> +            {' '}
oops no reason, ill remove that

2022-04-21 15:14 UTC, onb6 commented on src/components/survey/ConfirmReviewerIdentity.tsx
> +            wroker, your responses will be used to generate a letter of recommendation. You will
ah good catch!!

2022-04-21 21:31 UTC, rymaju approved these changes
LGTM

2022-04-21 21:31 UTC, rymaju commented
But a better PR title would be appreciated in the future!

2022-04-21 22:31 UTC, merged